[build]
command = "bundle exec jekyll build"
publish = "_site"
functions = "functions"

[build.environment]
RUBY_VERSION = "2.7.8"
BUNDLER_VERSION = "2.3.4"
NODE_VERSION = "20"
JEKYLL_ENV = "production"
